window.PAD_CONFIG = [
  { name: "엏", file: "ugh.m4a" },
  { name: "뿡", file: "fart.m4a" },
  { name: "꺽", file: "gguck.m4a" },
  { name: "인간", file: "ingan.m4a" },
  { name: "여자", file: "yeoja.m4a" },
  { name: "여자2", file: "yeoja2.m4a" },
  { name: "옵", file: "op.m4a" },
  { name: "오빠", file: "oppan.m4a" },
  { name: "에에", file: "ehhhh.m4a" },
  { name: "에에x6", file: "ehx6.m4a" },
  { name: "울퉁불퉁", file: "ultungbultung.m4a" },
  { name: "강남스타일", file: "ganamstyle.m4a" },
  { name: "강남", file: "gangnam.m4a" },
  { name: "헤이", file: "hey.m4a" },
  { name: "머리푸는", file: "meoripu.m4a" },
  { name: "미쳐", file: "micheo.m4a" },
  { name: "사나이", file: "sanai.m4a" },
];
